# Functions

In [3]:
def convert_length(value, from_unit):
    """
    Convert length between meters and feet.
    :param value: The numeric value to convert.
    :param from_unit: The unit to convert from ('m' or 'ft').
    :return: The converted value.
    """
    if from_unit == "m":
        return value * 3.28084  # meters to feet
    elif from_unit == "ft":
        return value / 3.28084  # feet to meters
    else:
        raise ValueError("Invalid length unit!")

def convert_weight(value, from_unit):
    """
    Convert weight between kilograms and pounds.
    """
    if from_unit == "kg":
        return value * 2.20462  # kg to lbs
    elif from_unit == "lbs":
        return value / 2.20462  # lbs to kg
    else:
        raise ValueError("Invalid weight unit!")

def convert_volume(value, from_unit):
    """
    Convert volume between liters and gallons.
    """
    if from_unit == "L":
        return value * 0.264172  # liters to gallons
    elif from_unit == "gal":
        return value / 0.264172  # gallons to liters
    else:
        raise ValueError("Invalid volume unit!")

def main_conversion():
    try:
        conversion_type = input("Choose conversion type (length/weight/volume): ").strip().lower()
        value = float(input("Enter value to convert: "))
        unit = input("Enter the unit: ").strip().lower()

        if conversion_type == "length":
            result = convert_length(value, unit)
        elif conversion_type == "weight":
            result = convert_weight(value, unit)
        elif conversion_type == "volume":
            result = convert_volume(value, unit)
        else:
            print("Invalid conversion type!")
            return

        print(f"Converted value: {result}")
    except ValueError as e:
        print(f"Error: {e}")

# Uncomment to run:
main_conversion()

Choose conversion type (length/weight/volume): length
Enter value to convert: 20
Enter the unit: m
Converted value: 65.6168

In [6]:
def calculate_sum(lst):
    """Returns the sum of a list of numbers."""
    return sum(lst)

def calculate_average(lst):
    """Returns the average of a list of numbers."""
    return sum(lst) / len(lst) if lst else 0

def calculate_max(lst):
    """Returns the maximum number from a list."""
    return max(lst)

def calculate_min(lst):
    """Returns the minimum number from a list."""
    return min(lst)

def main_math_operations():
    try:
        operation = input("Choose an operation (sum/average/max/min): ").strip().lower()
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: No numbers provided!")
            return

        if operation == "sum":
            result = calculate_sum(numbers)
        elif operation == "average":
            result = calculate_average(numbers)
        elif operation == "max":
            result = calculate_max(numbers)
        elif operation == "min":
            result = calculate_min(numbers)
        else:
            print("Invalid operation!")
            return

        print(f"Result: {result}")
    except ValueError:
        print("Error: Please enter valid numbers!")

# Uncomment to run:
main_math_operations()

Choose an operation (sum/average/max/min): sum
Enter numbers separated by spaces: 4 5
Result: 9.0

# List Manipulation

In [10]:
def extract_every_other(lst):
    """Returns every other element from the list."""
    return lst[::2]
extract_every_other([1, 2, 3, 4, 5, 6], )

[1, 3, 5]

In [11]:
def get_sublist(lst, start, end):
    """Returns a sublist from start to end index (inclusive)."""
    return lst[start:end+1]
get_sublist([1, 2, 3, 4, 5, 6],2,4)

[3, 4, 5]

In [12]:
def reverse_list(lst):
    """Returns the reversed list using slicing."""
    return lst[::-1]
reverse_list([1, 2, 3, 4, 5])

[5, 4, 3, 2, 1]

In [13]:
def remove_first_last(lst):
    """Removes the first and last elements from the list."""
    return lst[1:-1]
remove_first_last([1, 2, 3, 4, 5])

[2, 3, 4]

In [14]:
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]
get_first_n([1, 2, 3, 4, 5],3)

[1, 2, 3]

In [15]:
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]
get_last_n([1, 2, 3, 4, 5],2)

[4, 5]

In [16]:
def reverse_skip(lst):
    """Returns every second element in reverse order, starting from the second-to-last."""
    return lst[-2::-2]
reverse_skip([1, 2, 3, 4, 5, 6])

[5, 3, 1]

# Nested List

In [17]:
def flatten(lst):
    """Flattens a nested list into a single list. """

    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

flatten([[1, 2], [3, [4, 5]], 6])

[1, 2, 3, 4, 5, 6]

In [19]:
def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    for index in indices:
        lst = lst[index]
    return lst
access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]],[1,2])

6

In [20]:
def sum_nested(lst):
    """Calculates the sum of all the numbers in a nested list."""
    return sum(flatten(lst))

sum_nested([[1, 2], [3, [4, 5]], 6])

21

In [21]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

remove_element([[1, 2], [3, 2], [4, 5]],2)

[[1], [3], [4, 5]]

In [22]:
def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

find_max([[1, 2], [3, [4, 5]], 6])

6

In [23]:
def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list. """
    return flatten(lst).count(elem)
count_occurrences([[1, 2], [2, 3], [2, 4]],2)

3

In [24]:
def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

[1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)
average_nested([[1, 2], [3, 4], [5, 6]])

3.5

# Basic Vector and Matrix Operation with Numpy.

In [34]:
import numpy as np

In [46]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)
print("---------------")

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("All Ones 4x2 Array:\n", ones_array)
print("---------------")

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 2) #3x3, Fill Value: 2
print("Array Filled with Value 5:\n", fill_value_array)
print("---------------")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros Array with Same Shape as Given Array:\n", zeros_like_array)
print("---------------")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones Array with Same Shape as Given Array:\n", ones_like_array)
print("---------------")

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array from List:\n", numpy_array)

Empty 2x2 Array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
---------------
All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
Array Filled with Value 5:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
---------------
Zeros Array with Same Shape as Given Array:
 [[0 0]
 [0 0]]
---------------
Ones Array with Same Shape as Given Array:
 [[1 1]
 [1 1]]
---------------
Converted NumPy Array from List:
 [1 2 3 4]

In [47]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with Values from 10 to 49:\n", range_array)
print("---------------")

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with Values 0 to 8:\n", matrix_3x3)
print("---------------")

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
print("---------------")

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array of Size 30:\n", random_array)
print("Mean of Random Array:", mean_value)
print("---------------")

# 5. Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("---------------")

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("Zero Array with 5th Element Replaced:\n", zero_array)
print("---------------")

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)
print("---------------")

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)
print("---------------")

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

Array with Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array of Size 30:
 [0.49167699 0.14790665 0.53355453 0.30718724 0.30897996 0.09626603
 0.2759793  0.96370071 0.30213384 0.4146892  0.70868907 0.18239169
 0.37737535 0.18074866 0.35967152 0.98366726 0.30728787 0.34090929
 0.17066144 0.99934255 0.86483117 0.96907955 0.95465514 0.70579041
 0.94388795 0.3354727  0.71945611 0.20310159 0.92183309 0.18634494]
Mean of Random Array: 0.5085757264578078
---------------
10x10 Random Array:
 [[0.00270081 0.97360368 0.19491712 0.50956095 0.65001543 0.1207408
  0.26198763 0.10267178 0.60728292 0.0437599 ]
 [0.17550292 0.70950677 0.09622437 0.20749677 0.7860765  0.00617487
  0.80642571 0.30214881 0.18188    0.82830881]
 [0.53255398 0.86857566 0.64764322 0.93793748 0.1693991  0.42302599
  0.06077484 0.57148913 0.2502667  0.98736252]
 [0.40667099 0.83246195 0.3400252  0.20561251 0.7740741  0.83822751
  0.80469323 0.65838802 0.29950488 0.22857535]
 [0.77024369 0.14558608 0.50151741 0.30335292 0.11249543 0.72586077
  0.08008887 0.73033462 0.56281717 0.93659627]
 [0.36926834 0.23518136 0.8645427  0.08960015 0.95768047 0.71348526
  0.64028567 0.47948725 0.9197418  0.0976682 ]
 [0.60964233 0.02712382 0.35304857 0.59774114 0.28696192 0.92724374
  0.83545102 0.17704483 0.05800365 0.40990688]
 [0.07915048 0.30149539 0.63415497 0.01601708 0.59153411 0.7723594
  0.71110779 0.52552359 0.38168812 0.96082486]
 [0.91801536 0.1792027  0.10459923 0.23396186 0.92902294 0.79243724
  0.25870501 0.78475498 0.99112359 0.76961066]
 [0.23407798 0.87560856 0.45509358 0.14228087 0.45136057 0.63208043
  0.33995434 0.06101889 0.27110631 0.54511282]]
Minimum Value: 0.0027008114331971145
Maximum Value: 0.9911235870475777
---------------
Zero Array with 5th Element Replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
---------------
Reversed Array:
 [0 4 0 0 2 1]
---------------
2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
---------------
8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

In [49]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Sum
add_result = x + y
print("Addition of x and y:\n", add_result)
print("---------------")

# 2. Difference
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)
print("---------------")

# 3. Multiplication
multiply_result = x * 2
print("Multiplication of x by 2:\n", multiply_result)
print("---------------")

# 4. Square of each element
square_result = np.square(x)
print("Square of Each Element in x:\n", square_result)
print("---------------")

# 5. Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:\n", dot_xy)
print("---------------")

# 6. Concatenate x and y along rows, and v and w along columns
concatenate_rows = np.concatenate((x, y), axis=0)
concatenate_columns = np.vstack((v, w))
print("Concatenate x and y along rows:\n", concatenate_rows)
print("Concatenate v and w along columns:\n", concatenate_columns)
print("---------------")

# 7. Concatenate x and v (will raise an error)
try:
    concatenate_xv = np.concatenate((x, v))
except ValueError as e:
    print("Error:", e)
    print("Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.")

Addition of x and y:
 [[ 6  8]
 [10 13]]
---------------
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
---------------
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of Each Element in x:
 [[ 1  4]
 [ 9 25]]
---------------
Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]
---------------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.

In [41]:
# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A.A^-1:\n", identity_check)
print("---------------")

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB != BA?", not np.array_equal(AB, BA))
print("---------------")

# 3. Prove (AB)^T = B^T A^T
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("Is (AB)^T == B^T A^T?", np.array_equal(AB_transpose, B_transpose_A_transpose))
print("---------------")

# Solve the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
print("---------------")

# Inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution using Inverse Method:", X)
print("---------------")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_solve)

A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB != BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T == B^T A^T? True
---------------
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]